#!/bin/bash
echo "--- grep select('*') ---"
grep -n "select('*')" src/pages/[...slug].astro || echo "No matches"
echo "--- grep rawSections ---"
grep -n "const { data: rawSections" src/pages/[...slug].astro || echo "No matches"
echo "--- grep internalLinks ---"
grep -n "const { data: internalLinks" src/pages/[...slug].astro || echo "No matches"
echo "--- grep robots ---"
grep -n "const robots" src/pages/[...slug].astro || echo "No matches"
echo "--- grep configRows ---"
grep -n "const { data: configRows" src/pages/[...slug].astro || echo "No matches"
echo "--- grep faqs ---"
grep -n "const { data: faqs" src/pages/[...slug].astro || echo "No matches"
echo "--- grep gallery ---"
grep -n "const { data: gallery" src/pages/[...slug].astro || echo "No matches"
echo "--- grep <Image ---"
grep -n "<Image" src/pages/[...slug].astro || echo "No matches"
